# Generated by Django 3.2.4 on 2021-06-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('fsc', models.CharField(max_length=10)),
                ('niin', models.CharField(max_length=20)),
                ('unit_price', models.FloatField()),
                ('unit_issue', models.CharField(max_length=10)),
                ('shelf_life', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField()),
                ('course_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_requesting', models.CharField(max_length=20)),
                ('user_deliver', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.course')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('purchase_order', models.CharField(max_length=10)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('date_shelflife', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('login_user', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.owner')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable')),
            ],
        ),
        migrations.CreateModel(
            name='LocationConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'unique_together': {('consumable', 'location')},
            },
        ),
    ]
