# Generated by Django 3.2.4 on 2021-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location_consumable',
            new_name='LocationConsumable',
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
