# Generated by Django 3.2.4 on 2021-06-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Requisition',
        ),
        migrations.RenameField(
            model_name='exit',
            old_name='count_order',
            new_name='count_requisition',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='count_order',
            new_name='count_requisition',
        ),
    ]
