# Generated by Django 3.2.4 on 2021-06-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210621_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='date',
            new_name='date_requisition',
        ),
    ]
