# Generated by Django 3.2.4 on 2021-06-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210618_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('count', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('course_number', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField()),
                ('user_requesting', models.CharField(max_length=20)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.course')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable')),
            ],
        ),
    ]
