# Generated by Django 3.2.4 on 2021-06-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exit',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exit',
            name='user_requesting',
        ),
        migrations.AddField(
            model_name='exit',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('declined', 'Cancelado'), ('delivered', 'Entregado')], default='pending', max_length=30),
        ),
    ]
