# Generated by Django 3.2.4 on 2021-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210608_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
